#+BEGIN_COMMENT
.. title: Загоны
.. slug: arch-rel-zagony
.. date: 2021-06-15 21:19:07 UTC+03:00
.. tags: 
.. category: 
.. link: 
.. description: 
.. type: text

#+END_COMMENT

* Оля: как мы путаем "должен, хочу, боюсь, могу"
  1) Что я должен?
  2) Чего я хочу?
  3) Чего я боюсь?
  4) Что я могу?

  Оля говорит, что Фрейд утверждает: мы путаем ответы на эти вопросы
  и, по его мнению, под каждым пунком мы отвечаем на другие вопросы:
  1) Пишем то,чего я не хочу
  2) Не могу
  3) Хочу
  4) Боюсь
     
** Пример
   1) =Я должен= быть в силах забоиться об Алёне. По мнению Оли и ее интерпретации
      Фрейда, я =не хочу= заботиться об Алёне. Оля предлагает переформулировать
      =Я должен= в =Я могу или я не могу=.

      Я могу заботиться, а могу не забоиться. Это про интенцию, а не про то,
      что я что-то должен. С этим уже можно работать и развивать идею интенции -
      когда могу, а когда не могу?

   2) =Я хочу= безусловной любви. Чтобы отношения строились вокруг интенции
      быть вместе, что-то вместе делать, а не вокуг ожиданий и требований

      По Олиной интерпретации Фрейда, я этого =не могу=. Раз не могу, то и
      делаю. Оля предлагет ответить на вопрос: какие ресурсы у меня есть, а
      какие нужны для этого желания? Что я с этим =могу= сделать?

   3) =Я боюсь=, что от меня в отношениях начнут много требовать, а я
      перестану получать приятные плюшки от отношений

      ..., я этого =хочу=. Это сценарное требование

   4) =Я могу= обрадовать Алёну

      ..., я этого =боюсь=. Оля предлагате ответить на вопрос: какие плюсы
      я получу, если начну делать то, что написал в пункте 4), и какие минусы
      испытает мой сценарий? Как иначу воплощать то, что =хочу= - не то как
      мне это предлагеает мой сценарий, а более предпочитаемо, какие есть
      способы?

#+BEGIN_QUOTE
Я пережил многое в своей жизни, что со мной
не случилось -- Марк Твен
#+END_QUOTE

* Загоны в отношениях

 [[file:~/Dropbox/Org/Тест Петровского (категории принятия ранних решений).docx][КАТЕГОРИИ РАННИХ РЕШЕНИЙ (тест В.Петровского)]] 
