* Data science portfolio by Max Drobin
** Выпускная квалификационная работа в бакалавриате "Прогнозирование температуры во времени и пространства"
 https://github.com/gazon1/diplom-bachelor. Автоматизировал сбор данных с метеорологических станций по API через python3 и библиотеку requests. Обучил нейросеть на keras и ансамбль деревье по методу градиентного бустинга и сравнил качество прогноза для городов вблизи Лондона.
 
** NLP
*** Классификатор по предсказанию категории обьявления по цене, описанию, заголовку
Итоговое решение - стекинг FastText классификатора и xgboost
https://github.com/gazon1/testing-task-Avito

*** Sentiment analysis of movie review. Django
Приложение на django. Оно состоит из одной формы - в него можно написать
отзыв на фильм на англ и посмотреть тональность отзыва. Тональность предсказывается
Bert модель.
https://github.com/gazon1/GreenAtom
*** Прототип навигации в колекции видео Постнауки методом тематического моделирования 
https://github.com/gazon1/post-nauka-project/blob/master/PostnaukaPeerReview.ipynb

