* Data science portfolio by Max Drobin
** Выпускная квалификационная работа в бакалавриате "Прогнозирование температуры во времени и пространства"
 https://github.com/gazon1/diplom-bachelor. Автоматизировал сбор данных с метеорологических станций по API через python3 и библиотеку requests. Обучил нейросеть на keras и ансамбль деревье по методу градиентного бустинга и сравнил качество прогноза для городов вблизи Лондона.
 
** NLP
*** Классификатор по предсказанию категории обьявления по цене, описанию, заголовку
Итоговое решение - стекинг FastText классификатора и xgboost
https://github.com/gazon1/testing-task-Avito

*** Sentiment analysis of movie review. Django
Приложение на django. Оно состоит из одной формы - в него можно написать
отзыв на фильм на англ и посмотреть тональность отзыва. Тональность предсказывается
Bert модель.
https://github.com/gazon1/GreenAtom
*** Прототип навигации в колекции видео Постнауки методом тематического моделирования 
https://github.com/gazon1/post-nauka-project/blob/master/PostnaukaPeerReview.ipynb

** Recommendation systems
*** REKKO CHALLENGE (boosters)
https://boosters.pro/championship/rekko_challenge/overview
Соревнование по машинному обучению от онлайн-кинотеатра Okko. Обучите рекомендательную систему и предскажите предпочтения пользователей.
https://github.com/gazon1/Recco-challenge

** Kaggle competitions
*** Predict Future Sales
This challenge serves as final project for the "How to win a data science competition" Coursera course.

In this competition you will work with a challenging time-series dataset consisting of daily sales data, kindly provided by one of the largest Russian software firms - 1C Company. 

We are asking you to predict total sales for every product and store in the next month. By solving this competition you will be able to apply and enhance your data science skills.
https://github.com/gazon1/1c
** Kaggle kernels
*** Real or Not? NLP with Disaster Tweets
In this competition, you’re challenged to build a machine learning model that predicts which Tweets are about real disasters and which one’s aren’t. You’ll have access to a dataset of 10,000 tweets that were hand classified 

https://www.kaggle.com/malahai/lightgbm-tf-idf-baseline
*** Predict future sales
This challenge serves as final project for the "How to win a data science competition" Coursera course.

In this competition you will work with a challenging time-series dataset consisting of daily sales data, kindly provided by one of the largest Russian software firms - 1C Company. 

We are asking you to predict total sales for every product and store in the next month. By solving this competition you will be able to apply and enhance your data science skills.
https://www.kaggle.com/malahai/0-90-lb-feature-engineering-hyperopt-lightgbm
*** Cleaned vs Dirty V2
Hi! It is boring to wash the dishes. Luckily, half of them are already clean. Train a classifier to determine clean ones to save time for the new machine learning course ;)

It is a few shot learning competition. We have a dataset of 20 clean and 20 dirty plates in train and hundreds of plates in test. Good luck!
https://www.kaggle.com/malahai/resnet34-90-epoch
