* Data science portfolio by Max Drobin
** Stand-alone projects
*** Выпускная квалификационная работа в бакалавриате "Прогнозирование температуры во времени и пространства"
 https://github.com/gazon1/diplom-bachelor. Автоматизировал сбор данных с метеорологических станций по API через python3 и библиотеку requests. Обучил нейросеть на keras и ансамбль деревье по методу градиентного бустинга и сравнил качество прогноза для городов вблизи Лондона.
 
*** Предсказание исхода матча в Dota
Задача: предсказание победы по данным о первых 5 минутах игры

По первым 5 минутам игры предсказать, какая из команд победит: Radiant или Dire?

https://github.com/gazon1/hse_ml_coursera/blob/master/final-statement.ipynb
** NLP
*** Классификатор по предсказанию категории обьявления по цене, описанию, заголовку
Итоговое решение - стекинг FastText классификатора и xgboost
https://github.com/gazon1/testing-task-Avito

*** Sentiment analysis of movie review. Django
Приложение на django. Оно состоит из одной формы - в него можно написать
отзыв на фильм на англ и посмотреть тональность отзыва. Тональность предсказывается
Bert модель.
https://github.com/gazon1/GreenAtom
*** Прототип навигации в колекции видео Постнауки методом тематического моделирования 
https://github.com/gazon1/post-nauka-project/blob/master/PostnaukaPeerReview.ipynb

** Recommendation systems
*** REKKO CHALLENGE (boosters)
https://boosters.pro/championship/rekko_challenge/overview
Соревнование по машинному обучению от онлайн-кинотеатра Okko. Обучите рекомендательную систему и предскажите предпочтения пользователей.
https://github.com/gazon1/Recco-challenge

** Time series
*** EDA и анализ промо акций минеральной воды в магазине Окей
Задача: проанализировать выгоду от проведения промо акции
https://github.com/gazon1/Predicting-influence-of-promo
** Kaggle competitions
*** Predict Future Sales
This challenge serves as final project for the "How to win a data science competition" Coursera course.

In this competition you will work with a challenging time-series dataset consisting of daily sales data, kindly provided by one of the largest Russian software firms - 1C Company. 

We are asking you to predict total sales for every product and store in the next month. By solving this competition you will be able to apply and enhance your data science skills.
https://github.com/gazon1/1c
*** Real or Not? NLP with Disaster Tweets                               :NLP:
In this competition, you’re challenged to build a machine learning model that predicts which Tweets are about real disasters and which one’s aren’t. You’ll have access to a dataset of 10,000 tweets that were hand classified 

- [[https://www.kaggle.com/malahai/lightgbm-tf-idf-baseline][lightfm tf-idf baseline]] 0 LB. Понял, что нужна модель посложнее и перешел к нейросетям
- [[https://github.com/gazon1/Disaster_tweet][Pytorch LSTM]] 0.54 LB
*** Predict future sales
This challenge serves as final project for the "How to win a data science competition" Coursera course.

In this competition you will work with a challenging time-series dataset consisting of daily sales data, kindly provided by one of the largest Russian software firms - 1C Company. 

We are asking you to predict total sales for every product and store in the next month. By solving this competition you will be able to apply and enhance your data science skills.
https://www.kaggle.com/malahai/0-90-lb-feature-engineering-hyperopt-lightgbm
*** Cleaned vs Dirty V2                                                  :CV:
Hi! It is boring to wash the dishes. Luckily, half of them are already clean. Train a classifier to determine clean ones to save time for the new machine learning course ;)

It is a few shot learning competition. We have a dataset of 20 clean and 20 dirty plates in train and hundreds of plates in test. Good luck!
h
