#+BEGIN_COMMENT
.. title: Архитектура отношений
.. slug: 20210424143832-сценарии.org
.. date: 2021-06-15 21:19:07 UTC+03:00
.. tags: 
.. category: 
.. link: 
.. description: 
.. type: text

#+END_COMMENT

На наши отношения влияет то, каких отношений и жизни вообще желает наш [[link:posts/20210424145800-родитель_ребенок_взрослыи.org.html][Родитель]].
В Сценарии лежит идея обучения и повторения за взрослыми в детстве некоторых истин о жизни, словно
ребенок - это пластинка, на которую записывают как и что делать, а когда ребенок вырастает, пластинка
в роли [[file:20210424145800-родитель_ребенок_взрослыи.org][Родитель]] воспроизводит эти истины уже в разговорах и отношениях. Эта же пластинка
предлагает [[file:20210424145800-родитель_ребенок_взрослыи.org][Ребенку]] что чувстовать и что замечать в отношениях, а чего не замечать даже перед носом

- иногда детей поощряют и наказывают, а не обьясняют, почему нужно делаить или думать
  так, а не иначе. Это выгодно взрослым, им нужно, что дети их слушались
- противоречия иногда рождаются через "Двойной сигнал": пить алкоголь плохо, но родителям можно. Т.е.
  взрослым можно. Отсюда можно сделать вывод - вырасту, смогу пить алкоголь как и сколько захочу

В нарративной практике такие истины понижаются во власти через [[file:20210424162416-деконструкция.org][деконструкцию]] 

* Какую жизнь желает мне Родитель?
  Сценарий предлагает, что говорить [[file:20210424145800-родитель_ребенок_взрослыи.org][Родителю]] и что чувстовать ребенку [[file:20210424145800-родитель_ребенок_взрослыи.org][Ребенку]]. Из-за
  этого мы иногда не понимаем друг друга и вообще примитивно конструируем реальность, чтобы
  о чем-то договориться

  Сценарий тесно связан с теми [[link:posts/20210424123944-загоны_и_разрешения_себе_и_партнеру_на_это_ок_быть_таким.org.html][Директивами]], которым ищу подтверждение в отношениях.
  Есть директым связанные с несправедливость, унижением, предательством... Если концетрироваться
  на этом, то можно только и заниматься тем, что искать в отношениях подтверждений того, что вас
  партнер унижает, как-то несправидливо относится к вам и т.д. См. [[file:20210424151125-теорема_томаса.org][Теорему Томаса]] 
